/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Source: emojis.json
 * Generator: scripts/gen-emoji-ts.cjs
 */

const BASE: Record<string, string> = {
  "100": "💯",
  "1234": "🔢",
  "8ball": "🎱",
  _1: "👎",
  a: "🅰️",
  ab: "🆎",
  abacus: "🧮",
  abc: "🔤",
  abcd: "🔡",
  accept: "🉑",
  accordion: "🪗",
  adhesive_bandage: "🩹",
  adult: "🧑",
  aerial_tramway: "🚡",
  airplane: "✈️",
  airplane_arriving: "🛬",
  airplane_departure: "🛫",
  airplane_small: "🛩️",
  alarm_clock: "⏰",
  alembic: "⚗️",
  ambulance: "🚑",
  amphora: "🏺",
  anatomical_heart: "🫀",
  anchor: "⚓",
  angel: "👼",
  anger: "💢",
  anger_right: "🗯️",
  angry: "😠",
  ant: "🐜",
  apple: "🍎",
  aquarius: "♒",
  archery: "🏹",
  aries: "♈",
  arrow_backward: "◀️",
  arrow_double_down: "⏬",
  arrow_double_up: "⏫",
  arrow_down: "⬇️",
  arrow_down_small: "🔽",
  arrow_forward: "▶️",
  arrow_heading_down: "⤵️",
  arrow_heading_up: "⤴️",
  arrow_left: "⬅️",
  arrow_lower_left: "↙️",
  arrow_lower_right: "↘️",
  arrow_right: "➡️",
  arrow_right_hook: "↪️",
  arrow_up: "⬆️",
  arrow_up_down: "↕️",
  arrow_up_small: "🔼",
  arrow_upper_left: "↖️",
  arrow_upper_right: "↗️",
  arrows_clockwise: "🔃",
  arrows_counterclockwise: "🔄",
  art: "🎨",
  articulated_lorry: "🚛",
  artist: "🧑‍🎨",
  astronaut: "🧑‍🚀",
  athletic_shoe: "👟",
  atm: "🏧",
  atom: "⚛️",
  auto_rickshaw: "🛺",
  avocado: "🥑",
  axe: "🪓",
  b: "🅱️",
  baby: "👶",
  baby_bottle: "🍼",
  baby_chick: "🐤",
  baby_symbol: "🚼",
  back: "🔙",
  back_of_hand: "🤚",
  bacon: "🥓",
  badger: "🦡",
  badminton: "🏸",
  bagel: "🥯",
  baggage_claim: "🛄",
  ballet_shoes: "🩰",
  balloon: "🎈",
  ballot_box: "🗳️",
  ballot_box_with_check: "☑️",
  bamboo: "🎍",
  banana: "🍌",
  bangbang: "‼️",
  banjo: "🪕",
  bank: "🏦",
  bar_chart: "📊",
  barber: "💈",
  baseball: "⚾",
  basket: "🧺",
  basketball: "🏀",
  bat: "🦇",
  bath: "🛀",
  bathtub: "🛁",
  battery: "🔋",
  beach: "🏖️",
  beach_umbrella: "⛱️",
  bear: "🐻",
  bearded_person: "🧔",
  beaver: "🦫",
  bed: "🛏️",
  bee: "🐝",
  beer: "🍺",
  beers: "🍻",
  beetle: "🪲",
  beginner: "🔰",
  bell: "🔔",
  bell_pepper: "🫑",
  bellhop: "🛎️",
  bento: "🍱",
  beverage_box: "🧃",
  bicyclist: "🚴",
  bike: "🚲",
  bikini: "👙",
  billed_cap: "🧢",
  biohazard: "☣️",
  bird: "🐦",
  birthday: "🎂",
  bison: "🦬",
  black_cat: "🐈‍⬛",
  black_circle: "⚫",
  black_heart: "🖤",
  black_joker: "🃏",
  black_large_square: "⬛",
  black_medium_small_square: "◾",
  black_medium_square: "◼️",
  black_nib: "✒️",
  black_small_square: "▪️",
  black_square_button: "🔲",
  blond_haired_man: "👱‍♂️",
  blond_haired_person: "👱",
  blond_haired_woman: "👱‍♀️",
  blossom: "🌼",
  blowfish: "🐡",
  blue_book: "📘",
  blue_car: "🚙",
  blue_circle: "🔵",
  blue_heart: "💙",
  blue_square: "🟦",
  blueberries: "🫐",
  blush: "😊",
  boar: "🐗",
  bomb: "💣",
  bone: "🦴",
  book: "📖",
  bookmark: "🔖",
  bookmark_tabs: "📑",
  books: "📚",
  boom: "💥",
  boomerang: "🪃",
  boot: "👢",
  bouquet: "💐",
  bow: "🙇",
  bowl_with_spoon: "🥣",
  bowling: "🎳",
  boxing_glove: "🥊",
  boy: "👦",
  brain: "🧠",
  bread: "🍞",
  breast_feeding: "🤱",
  bricks: "🧱",
  bride_with_veil: "👰‍♀️",
  bridge_at_night: "🌉",
  briefcase: "💼",
  briefs: "🩲",
  broccoli: "🥦",
  broken_heart: "💔",
  broom: "🧹",
  brown_circle: "🟤",
  brown_heart: "🤎",
  brown_square: "🟫",
  bubble_tea: "🧋",
  bucket: "🪣",
  bug: "🐛",
  bulb: "💡",
  bullettrain_front: "🚅",
  bullettrain_side: "🚄",
  burrito: "🌯",
  bus: "🚌",
  busstop: "🚏",
  bust_in_silhouette: "👤",
  busts_in_silhouette: "👥",
  butter: "🧈",
  butterfly: "🦋",
  cactus: "🌵",
  cake: "🍰",
  calendar: "📆",
  calendar_spiral: "🗓️",
  call_me: "🤙",
  calling: "📲",
  camel: "🐫",
  camera: "📷",
  camera_with_flash: "📸",
  camping: "🏕️",
  cancer: "♋",
  candle: "🕯️",
  candy: "🍬",
  canned_food: "🥫",
  canoe: "🛶",
  capital_abcd: "🔠",
  capricorn: "♑",
  card_box: "🗃️",
  card_index: "📇",
  carousel_horse: "🎠",
  carpentry_saw: "🪚",
  carrot: "🥕",
  cartwheel: "🤸",
  cat: "🐱",
  cat2: "🐈",
  cd: "💿",
  chains: "⛓️",
  chair: "🪑",
  champagne: "🍾",
  chart: "💹",
  chart_with_downwards_trend: "📉",
  chart_with_upwards_trend: "📈",
  checkered_flag: "🏁",
  cheese: "🧀",
  cherries: "🍒",
  cherry_blossom: "🌸",
  chess_pawn: "♟️",
  chestnut: "🌰",
  chicken: "🐔",
  child: "🧒",
  children_crossing: "🚸",
  chipmunk: "🐿️",
  chocolate_bar: "🍫",
  chopsticks: "🥢",
  christmas_tree: "🎄",
  church: "⛪",
  cinema: "🎦",
  circus_tent: "🎪",
  city_dusk: "🌆",
  city_sunset: "🌇",
  cityscape: "🏙️",
  cl: "🆑",
  clap: "👏",
  clapper: "🎬",
  classical_building: "🏛️",
  clinking_glass: "🥂",
  clipboard: "📋",
  clock: "🕰️",
  closed_book: "📕",
  closed_lock_with_key: "🔐",
  closed_umbrella: "🌂",
  cloud: "☁️",
  cloud_lightning: "🌩️",
  cloud_rain: "🌧️",
  cloud_snow: "🌨️",
  cloud_tornado: "🌪️",
  clubs: "♣️",
  coat: "🧥",
  cockroach: "🪳",
  cocktail: "🍸",
  coconut: "🥥",
  coffee: "☕",
  coffin: "⚰️",
  coin: "🪙",
  comet: "☄️",
  compass: "🧭",
  compression: "🗜️",
  computer: "💻",
  confetti_ball: "🎊",
  confused: "😕",
  congratulations: "㊗️",
  construction: "🚧",
  construction_site: "🏗️",
  construction_worker: "👷",
  control_knobs: "🎛️",
  convenience_store: "🏪",
  cook: "🧑‍🍳",
  cookie: "🍪",
  cooking: "🍳",
  cool: "🆒",
  cop: "👮",
  copyright: "©️",
  corn: "🌽",
  couch: "🛋️",
  couple: "👫",
  couple_mm: "👨‍❤️‍👨",
  couple_with_heart: "💑",
  couple_with_heart_woman_man: "👩‍❤️‍👨",
  couple_ww: "👩‍❤️‍👩",
  couplekiss: "💏",
  cow: "🐮",
  cow2: "🐄",
  crab: "🦀",
  crayon: "🖍️",
  credit_card: "💳",
  crescent_moon: "🌙",
  cricket: "🦗",
  cricket_game: "🏏",
  crocodile: "🐊",
  croissant: "🥐",
  cross: "✝️",
  crossed_flags: "🎌",
  crossed_swords: "⚔️",
  crown: "👑",
  cruise_ship: "🛳️",
  cry: "😢",
  crystal_ball: "🔮",
  cucumber: "🥒",
  cup_with_straw: "🥤",
  cupcake: "🧁",
  cupid: "💘",
  curling_stone: "🥌",
  curly_loop: "➰",
  currency_exchange: "💱",
  curry: "🍛",
  customs: "🛃",
  cut_of_meat: "🥩",
  cyclone: "🌀",
  dagger: "🗡️",
  dancer: "💃",
  dancers: "👯",
  dango: "🍡",
  dark_sunglasses: "🕶️",
  dart: "🎯",
  dash: "💨",
  date: "📅",
  deaf_man: "🧏‍♂️",
  deaf_person: "🧏",
  deaf_woman: "🧏‍♀️",
  deciduous_tree: "🌳",
  deer: "🦌",
  department_store: "🏬",
  desert: "🏜️",
  desktop: "🖥️",
  diamond_shape_with_a_dot_inside: "💠",
  diamonds: "♦️",
  dividers: "🗂️",
  diving_mask: "🤿",
  diya_lamp: "🪔",
  dizzy: "💫",
  dna: "🧬",
  do_not_litter: "🚯",
  dodo: "🦤",
  dog: "🐶",
  dog2: "🐕",
  dollar: "💵",
  dolls: "🎎",
  dolphin: "🐬",
  door: "🚪",
  doughnut: "🍩",
  dove: "🕊️",
  dragon: "🐉",
  dragon_face: "🐲",
  dress: "👗",
  dromedary_camel: "🐪",
  drop_of_blood: "🩸",
  droplet: "💧",
  drum: "🥁",
  duck: "🦆",
  dumpling: "🥟",
  dvd: "📀",
  eagle: "🦅",
  ear: "👂",
  ear_of_rice: "🌾",
  ear_with_hearing_aid: "🦻",
  earth_africa: "🌍",
  earth_americas: "🌎",
  earth_asia: "🌏",
  egg: "🥚",
  eggplant: "🍆",
  eight_pointed_black_star: "✴️",
  eight_spoked_asterisk: "✳️",
  eject: "⏏️",
  electric_plug: "🔌",
  elephant: "🐘",
  elevator: "🛗",
  elf: "🧝",
  email: "📧",
  end: "🔚",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  envelope: "✉️",
  envelope_with_arrow: "📩",
  euro: "💶",
  european_castle: "🏰",
  european_post_office: "🏤",
  evergreen_tree: "🌲",
  exclamation: "❗",
  eye: "👁️",
  eye_in_speech_bubble: "👁‍🗨",
  eyeglasses: "👓",
  eyes: "👀",
  facepalm: "🤦",
  factory: "🏭",
  factory_worker: "🧑‍🏭",
  fairy: "🧚",
  falafel: "🧆",
  fallen_leaf: "🍂",
  family: "👪",
  family_man_boy: "👨‍👦",
  family_man_boy_boy: "👨‍👦‍👦",
  family_man_girl: "👨‍👧",
  family_man_girl_boy: "👨‍👧‍👦",
  family_man_girl_girl: "👨‍👧‍👧",
  family_man_woman_boy: "👨‍👩‍👦",
  family_mmb: "👨‍👨‍👦",
  family_mmbb: "👨‍👨‍👦‍👦",
  family_mmg: "👨‍👨‍👧",
  family_mmgb: "👨‍👨‍👧‍👦",
  family_mmgg: "👨‍👨‍👧‍👧",
  family_mwbb: "👨‍👩‍👦‍👦",
  family_mwg: "👨‍👩‍👧",
  family_mwgb: "👨‍👩‍👧‍👦",
  family_mwgg: "👨‍👩‍👧‍👧",
  family_woman_boy: "👩‍👦",
  family_woman_boy_boy: "👩‍👦‍👦",
  family_woman_girl: "👩‍👧",
  family_woman_girl_boy: "👩‍👧‍👦",
  family_woman_girl_girl: "👩‍👧‍👧",
  family_wwb: "👩‍👩‍👦",
  family_wwbb: "👩‍👩‍👦‍👦",
  family_wwg: "👩‍👩‍👧",
  family_wwgb: "👩‍👩‍👧‍👦",
  family_wwgg: "👩‍👩‍👧‍👧",
  farmer: "🧑‍🌾",
  fast_forward: "⏩",
  fax: "📠",
  feather: "🪶",
  feet: "🐾",
  female_sign: "♀️",
  fencer: "🤺",
  ferris_wheel: "🎡",
  ferry: "⛴️",
  field_hockey: "🏑",
  file_cabinet: "🗄️",
  file_folder: "📁",
  film_frames: "🎞️",
  fingers_crossed: "🤞",
  fire: "🔥",
  fire_engine: "🚒",
  fire_extinguisher: "🧯",
  firecracker: "🧨",
  firefighter: "🧑‍🚒",
  fireworks: "🎆",
  first_place: "🥇",
  first_quarter_moon: "🌓",
  first_quarter_moon_with_face: "🌛",
  fish: "🐟",
  fish_cake: "🍥",
  fishing_pole_and_fish: "🎣",
  fist: "✊",
  flag_black: "🏴",
  flag_white: "🏳️",
  flags: "🎏",
  flamingo: "🦩",
  flan: "🍮",
  flashlight: "🔦",
  flatbread: "🫓",
  fleur_de_lis: "⚜️",
  floppy_disk: "💾",
  flower_playing_cards: "🎴",
  fly: "🪰",
  flying_disc: "🥏",
  flying_saucer: "🛸",
  fog: "🌫️",
  foggy: "🌁",
  fondue: "🫕",
  foot: "🦶",
  football: "🏈",
  footprints: "👣",
  fork_and_knife: "🍴",
  fork_knife_plate: "🍽️",
  fortune_cookie: "🥠",
  fountain: "⛲",
  four_leaf_clover: "🍀",
  fox: "🦊",
  frame_photo: "🖼️",
  free: "🆓",
  french_bread: "🥖",
  fried_shrimp: "🍤",
  fries: "🍟",
  frog: "🐸",
  frowning: "😦",
  frowning2: "☹️",
  fuelpump: "⛽",
  full_moon: "🌕",
  full_moon_with_face: "🌝",
  game_die: "🎲",
  garlic: "🧄",
  gear: "⚙️",
  gem: "💎",
  gemini: "♊",
  genie: "🧞",
  gift: "🎁",
  gift_heart: "💝",
  giraffe: "🦒",
  girl: "👧",
  globe_with_meridians: "🌐",
  gloves: "🧤",
  goal: "🥅",
  goat: "🐐",
  goggles: "🥽",
  golf: "⛳",
  golfer: "🏌️",
  gorilla: "🦍",
  grandma: "👵",
  grapes: "🍇",
  green_apple: "🍏",
  green_book: "📗",
  green_circle: "🟢",
  green_heart: "💚",
  green_square: "🟩",
  grey_exclamation: "❕",
  grey_question: "❔",
  guard: "💂",
  guide_dog: "🦮",
  guitar: "🎸",
  gun: "🔫",
  haircut: "💇",
  hamburger: "🍔",
  hammer: "🔨",
  hammer_pick: "⚒️",
  hamster: "🐹",
  hand_splayed: "🖐️",
  hand_with_index_and_middle_fingers_crossed: "🤞",
  handbag: "👜",
  handball: "🤾",
  handshake: "🤝",
  hatched_chick: "🐥",
  hatching_chick: "🐣",
  headphones: "🎧",
  headstone: "🪦",
  health_worker: "🧑‍⚕️",
  hear_no_evil: "🙉",
  heart: "❤️",
  heart_decoration: "💟",
  heart_exclamation: "❣️",
  heartbeat: "💓",
  heartpulse: "💗",
  hearts: "♥️",
  heavy_check_mark: "✔️",
  heavy_division_sign: "➗",
  heavy_dollar_sign: "💲",
  heavy_minus_sign: "➖",
  heavy_multiplication_x: "✖️",
  heavy_plus_sign: "➕",
  hedgehog: "🦔",
  helicopter: "🚁",
  helmet_with_cross: "⛑️",
  herb: "🌿",
  hibiscus: "🌺",
  high_brightness: "🔆",
  high_heel: "👠",
  hiking_boot: "🥾",
  hindu_temple: "🛕",
  hippopotamus: "🦛",
  hockey: "🏒",
  hole: "🕳️",
  homes: "🏘️",
  honey_pot: "🍯",
  hook: "🪝",
  horse: "🐴",
  horse_racing: "🏇",
  hospital: "🏥",
  hot_pepper: "🌶️",
  hotdog: "🌭",
  hotel: "🏨",
  hotsprings: "♨️",
  hourglass: "⌛",
  hourglass_flowing_sand: "⏳",
  house: "🏠",
  house_abandoned: "🏚️",
  house_with_garden: "🏡",
  hut: "🛖",
  ice_cream: "🍨",
  ice_cube: "🧊",
  ice_skate: "⛸️",
  icecream: "🍦",
  id: "🆔",
  ideograph_advantage: "🉐",
  imp: "👿",
  inbox_tray: "📥",
  incoming_envelope: "📨",
  infinity: "♾️",
  information_source: "ℹ️",
  innocent: "😇",
  interrobang: "⁉️",
  iphone: "📱",
  island: "🏝️",
  izakaya_lantern: "🏮",
  japan: "🗾",
  japanese_castle: "🏯",
  jeans: "👖",
  jigsaw: "🧩",
  joy: "😂",
  joystick: "🕹️",
  judge: "🧑‍⚖️",
  juggler: "🤹",
  kaaba: "🕋",
  kangaroo: "🦘",
  karate_uniform: "🥋",
  key: "🔑",
  key2: "🗝️",
  keyboard: "⌨️",
  kimono: "👘",
  kiss: "💋",
  kiss_mm: "👨‍❤️‍💋‍👨",
  kiss_woman_man: "👩‍❤️‍💋‍👨",
  kiss_ww: "👩‍❤️‍💋‍👩",
  kissing: "😗",
  kite: "🪁",
  kiwi: "🥝",
  knife: "🔪",
  knot: "🪢",
  koala: "🐨",
  koko: "🈁",
  lab_coat: "🥼",
  label: "🏷️",
  lacrosse: "🥍",
  ladder: "🪜",
  lady_beetle: "🐞",
  large_blue_diamond: "🔷",
  large_orange_diamond: "🔶",
  last_quarter_moon: "🌗",
  last_quarter_moon_with_face: "🌜",
  laughing: "😆",
  leafy_green: "🥬",
  leaves: "🍃",
  ledger: "📒",
  left_fist: "🤛",
  left_luggage: "🛅",
  left_right_arrow: "↔️",
  leftwards_arrow_with_hook: "↩️",
  leg: "🦵",
  lemon: "🍋",
  leo: "♌",
  leopard: "🐆",
  level_slider: "🎚️",
  levitate: "🕴️",
  libra: "♎",
  lifter: "🏋️",
  light_rail: "🚈",
  link: "🔗",
  lion: "🦁",
  lips: "👄",
  lipstick: "💄",
  lizard: "🦎",
  llama: "🦙",
  lobster: "🦞",
  lock: "🔒",
  lock_with_ink_pen: "🔏",
  lollipop: "🍭",
  long_drum: "🪘",
  loop: "➿",
  loud_sound: "🔊",
  loudspeaker: "📢",
  love_hotel: "🏩",
  love_letter: "💌",
  love_you_gesture: "🤟",
  low_brightness: "🔅",
  luggage: "🧳",
  lungs: "🫁",
  m: "Ⓜ️",
  mag: "🔍",
  mag_right: "🔎",
  mage: "🧙",
  magic_wand: "🪄",
  magnet: "🧲",
  mahjong: "🀄",
  mailbox: "📫",
  mailbox_closed: "📪",
  mailbox_with_mail: "📬",
  mailbox_with_no_mail: "📭",
  male_dancer: "🕺",
  male_sign: "♂️",
  mammoth: "🦣",
  man: "👨",
  man_artist: "👨‍🎨",
  man_astronaut: "👨‍🚀",
  man_bald: "👨‍🦲",
  man_biking: "🚴‍♂️",
  man_bouncing_ball: "⛹️‍♂️",
  man_bowing: "🙇‍♂️",
  man_cartwheeling: "🤸‍♂️",
  man_climbing: "🧗‍♂️",
  man_construction_worker: "👷‍♂️",
  man_cook: "👨‍🍳",
  man_curly_haired: "👨‍🦱",
  man_detective: "🕵️‍♂️",
  man_elf: "🧝‍♂️",
  man_facepalming: "🤦‍♂️",
  man_factory_worker: "👨‍🏭",
  man_fairy: "🧚‍♂️",
  man_farmer: "👨‍🌾",
  man_feeding_baby: "👨‍🍼",
  man_firefighter: "👨‍🚒",
  man_frowning: "🙍‍♂️",
  man_genie: "🧞‍♂️",
  man_gesturing_no: "🙅‍♂️",
  man_gesturing_ok: "🙆‍♂️",
  man_getting_face_massage: "💆‍♂️",
  man_getting_haircut: "💇‍♂️",
  man_golfing: "🏌️‍♂️",
  man_guard: "💂‍♂️",
  man_health_worker: "👨‍⚕️",
  man_in_lotus_position: "🧘‍♂️",
  man_in_manual_wheelchair: "👨‍🦽",
  man_in_motorized_wheelchair: "👨‍🦼",
  man_in_steamy_room: "🧖‍♂️",
  man_in_tuxedo: "🤵‍♂️",
  man_judge: "👨‍⚖️",
  man_juggling: "🤹‍♂️",
  man_kneeling: "🧎‍♂️",
  man_lifting_weights: "🏋️‍♂️",
  man_mage: "🧙‍♂️",
  man_mechanic: "👨‍🔧",
  man_mountain_biking: "🚵‍♂️",
  man_office_worker: "👨‍💼",
  man_pilot: "👨‍✈️",
  man_playing_handball: "🤾‍♂️",
  man_playing_water_polo: "🤽‍♂️",
  man_police_officer: "👮‍♂️",
  man_pouting: "🙎‍♂️",
  man_raising_hand: "🙋‍♂️",
  man_red_haired: "👨‍🦰",
  man_rowing_boat: "🚣‍♂️",
  man_running: "🏃‍♂️",
  man_scientist: "👨‍🔬",
  man_shrugging: "🤷‍♂️",
  man_singer: "👨‍🎤",
  man_standing: "🧍‍♂️",
  man_student: "👨‍🎓",
  man_superhero: "🦸‍♂️",
  man_supervillain: "🦹‍♂️",
  man_surfing: "🏄‍♂️",
  man_swimming: "🏊‍♂️",
  man_teacher: "👨‍🏫",
  man_technologist: "👨‍💻",
  man_tipping_hand: "💁‍♂️",
  man_vampire: "🧛‍♂️",
  man_walking: "🚶‍♂️",
  man_wearing_turban: "👳‍♂️",
  man_white_haired: "👨‍🦳",
  man_with_gua_pi_mao: "👲",
  man_with_probing_cane: "👨‍🦯",
  man_with_turban: "👳",
  man_with_veil: "👰‍♂️",
  man_zombie: "🧟‍♂️",
  mango: "🥭",
  mans_shoe: "👞",
  manual_wheelchair: "🦽",
  map: "🗺️",
  maple_leaf: "🍁",
  massage: "💆",
  mate: "🧉",
  meat_on_bone: "🍖",
  mechanic: "🧑‍🔧",
  mechanical_arm: "🦾",
  mechanical_leg: "🦿",
  medal: "🏅",
  medical_symbol: "⚕️",
  mega: "📣",
  melon: "🍈",
  memo: "📝",
  men_holding_hands: "👬",
  men_with_bunny_ears_partying: "👯‍♂️",
  men_wrestling: "🤼‍♂️",
  menorah: "🕎",
  mens: "🚹",
  mermaid: "🧜‍♀️",
  merman: "🧜‍♂️",
  merperson: "🧜",
  metal: "🤘",
  metro: "🚇",
  microbe: "🦠",
  microphone: "🎤",
  microphone2: "🎙️",
  microscope: "🔬",
  middle_finger: "🖕",
  military_helmet: "🪖",
  military_medal: "🎖️",
  milk: "🥛",
  milky_way: "🌌",
  minibus: "🚐",
  minidisc: "💽",
  mirror: "🪞",
  mobile_phone_off: "📴",
  money_with_wings: "💸",
  moneybag: "💰",
  monkey: "🐒",
  monkey_face: "🐵",
  monorail: "🚝",
  moon_cake: "🥮",
  mortar_board: "🎓",
  mosque: "🕌",
  mosquito: "🦟",
  motorbike: "🛵",
  motorboat: "🛥️",
  motorcycle: "🏍️",
  motorized_wheelchair: "🦼",
  motorway: "🛣️",
  mount_fuji: "🗻",
  mountain: "⛰️",
  mountain_bicyclist: "🚵",
  mountain_cableway: "🚠",
  mountain_railway: "🚞",
  mountain_snow: "🏔️",
  mouse: "🐭",
  mouse2: "🐁",
  mouse_three_button: "🖱️",
  mouse_trap: "🪤",
  movie_camera: "🎥",
  moyai: "🗿",
  mrs_claus: "🤶",
  muscle: "💪",
  mushroom: "🍄",
  musical_keyboard: "🎹",
  musical_note: "🎵",
  musical_score: "🎼",
  mute: "🔇",
  mx_claus: "🧑‍🎄",
  nail_care: "💅",
  name_badge: "📛",
  nazar_amulet: "🧿",
  necktie: "👔",
  negative_squared_cross_mark: "❎",
  nesting_dolls: "🪆",
  neutral_face: "😐",
  new: "🆕",
  new_moon: "🌑",
  new_moon_with_face: "🌚",
  newspaper: "📰",
  newspaper2: "🗞️",
  next_track: "⏭️",
  ng: "🆖",
  night_with_stars: "🌃",
  ninja: "🥷",
  no_bell: "🔕",
  no_bicycles: "🚳",
  no_entry: "⛔",
  no_entry_sign: "🚫",
  no_good: "🙅",
  no_mobile_phones: "📵",
  no_pedestrians: "🚷",
  no_smoking: "🚭",
  non_potable_water: "🚱",
  nose: "👃",
  notebook: "📓",
  notebook_with_decorative_cover: "📔",
  notepad_spiral: "🗒️",
  notes: "🎶",
  nut_and_bolt: "🔩",
  o: "⭕",
  o2: "🅾️",
  ocean: "🌊",
  octopus: "🐙",
  oden: "🍢",
  office: "🏢",
  office_worker: "🧑‍💼",
  oil: "🛢️",
  ok: "🆗",
  ok_hand: "👌",
  ok_woman: "🙆",
  older_adult: "🧓",
  older_man: "👴",
  olive: "🫒",
  om_symbol: "🕉️",
  on: "🔛",
  oncoming_automobile: "🚘",
  oncoming_bus: "🚍",
  oncoming_police_car: "🚔",
  oncoming_taxi: "🚖",
  one_piece_swimsuit: "🩱",
  onion: "🧅",
  open_file_folder: "📂",
  open_hands: "👐",
  open_mouth: "😮",
  ophiuchus: "⛎",
  orange_book: "📙",
  orange_circle: "🟠",
  orange_heart: "🧡",
  orange_square: "🟧",
  orangutan: "🦧",
  orthodox_cross: "☦️",
  otter: "🦦",
  outbox_tray: "📤",
  owl: "🦉",
  ox: "🐂",
  oyster: "🦪",
  package: "📦",
  paella: "🥘",
  page_facing_up: "📄",
  page_with_curl: "📃",
  pager: "📟",
  paintbrush: "🖌️",
  palm_tree: "🌴",
  pancakes: "🥞",
  panda_face: "🐼",
  paperclip: "📎",
  paperclips: "🖇️",
  parachute: "🪂",
  park: "🏞️",
  parking: "🅿️",
  parrot: "🦜",
  part_alternation_mark: "〽️",
  partly_sunny: "⛅",
  passport_control: "🛂",
  pause_button: "⏸️",
  peace: "☮️",
  peach: "🍑",
  peacock: "🦚",
  peanuts: "🥜",
  pear: "🍐",
  pen_ballpoint: "🖊️",
  pen_fountain: "🖋️",
  pencil2: "✏️",
  penguin: "🐧",
  pensive: "😔",
  people_holding_hands: "🧑‍🤝‍🧑",
  people_hugging: "🫂",
  performing_arts: "🎭",
  person_bald: "🧑‍🦲",
  person_climbing: "🧗",
  person_curly_hair: "🧑‍🦱",
  person_feeding_baby: "🧑‍🍼",
  person_frowning: "🙍",
  person_in_bed: "🛌",
  person_in_lotus_position: "🧘",
  person_in_manual_wheelchair: "🧑‍🦽",
  person_in_motorized_wheelchair: "🧑‍🦼",
  person_in_steamy_room: "🧖",
  person_in_tuxedo: "🤵",
  person_kneeling: "🧎",
  person_pouting: "🙎",
  person_red_hair: "🧑‍🦰",
  person_standing: "🧍",
  person_tipping_hand: "💁",
  person_tone1_bald: "🧑🏻‍🦲",
  person_tone1_curly_hair: "🧑🏻‍🦱",
  person_tone1_red_hair: "🧑🏻‍🦰",
  person_tone1_white_hair: "🧑🏻‍🦳",
  person_tone2_bald: "🧑🏼‍🦲",
  person_tone2_curly_hair: "🧑🏼‍🦱",
  person_tone2_red_hair: "🧑🏼‍🦰",
  person_tone2_white_hair: "🧑🏼‍🦳",
  person_tone3_bald: "🧑🏽‍🦲",
  person_tone3_curly_hair: "🧑🏽‍🦱",
  person_tone3_red_hair: "🧑🏽‍🦰",
  person_tone3_white_hair: "🧑🏽‍🦳",
  person_tone4_bald: "🧑🏾‍🦲",
  person_tone4_curly_hair: "🧑🏾‍🦱",
  person_tone4_red_hair: "🧑🏾‍🦰",
  person_tone4_white_hair: "🧑🏾‍🦳",
  person_tone5_bald: "🧑🏿‍🦲",
  person_tone5_curly_hair: "🧑🏿‍🦱",
  person_tone5_red_hair: "🧑🏿‍🦰",
  person_tone5_white_hair: "🧑🏿‍🦳",
  person_white_hair: "🧑‍🦳",
  person_with_ball: "⛹️",
  person_with_probing_cane: "🧑‍🦯",
  person_with_veil: "👰",
  petri_dish: "🧫",
  pick: "⛏️",
  pickup_truck: "🛻",
  pie: "🥧",
  pig: "🐷",
  pig2: "🐖",
  pig_nose: "🐽",
  pill: "💊",
  pilot: "🧑‍✈️",
  pinched_fingers: "🤌",
  pinching_hand: "🤏",
  pineapple: "🍍",
  ping_pong: "🏓",
  pirate_flag: "🏴‍☠️",
  pisces: "♓",
  pizza: "🍕",
  piñata: "🪅",
  placard: "🪧",
  play_pause: "⏯️",
  plunger: "🪠",
  point_down: "👇",
  point_left: "👈",
  point_right: "👉",
  point_up: "☝️",
  point_up_2: "👆",
  polar_bear: "🐻‍❄️",
  police_car: "🚓",
  poodle: "🐩",
  popcorn: "🍿",
  post_office: "🏣",
  postal_horn: "📯",
  postbox: "📮",
  potable_water: "🚰",
  potato: "🥔",
  potted_plant: "🪴",
  pouch: "👝",
  poultry_leg: "🍗",
  pound: "💷",
  pray: "🙏",
  prayer_beads: "📿",
  pregnant_woman: "🤰",
  pretzel: "🥨",
  previous_track: "⏮️",
  prince: "🤴",
  princess: "👸",
  printer: "🖨️",
  probing_cane: "🦯",
  projector: "📽️",
  punch: "👊",
  purple_circle: "🟣",
  purple_heart: "💜",
  purple_square: "🟪",
  purse: "👛",
  pushpin: "📌",
  put_litter_in_its_place: "🚮",
  question: "❓",
  rabbit: "🐰",
  rabbit2: "🐇",
  raccoon: "🦝",
  race_car: "🏎️",
  racehorse: "🐎",
  radio: "📻",
  radio_button: "🔘",
  radioactive: "☢️",
  rage: "😡",
  railway_car: "🚃",
  railway_track: "🛤️",
  rainbow: "🌈",
  rainbow_flag: "🏳️‍🌈",
  raised_hand: "✋",
  raised_hands: "🙌",
  raising_hand: "🙋",
  ram: "🐏",
  ramen: "🍜",
  rat: "🐀",
  razor: "🪒",
  receipt: "🧾",
  record_button: "⏺️",
  recycle: "♻️",
  red_car: "🚗",
  red_circle: "🔴",
  red_envelope: "🧧",
  red_square: "🟥",
  registered: "®️",
  reminder_ribbon: "🎗️",
  repeat: "🔁",
  repeat_one: "🔂",
  restroom: "🚻",
  revolving_hearts: "💞",
  rewind: "⏪",
  rhino: "🦏",
  ribbon: "🎀",
  rice: "🍚",
  rice_ball: "🍙",
  rice_cracker: "🍘",
  rice_scene: "🎑",
  right_fist: "🤜",
  "ring-3": "💍",
  ringed_planet: "🪐",
  rock: "🪨",
  rocket: "🚀",
  roll_of_paper: "🧻",
  roller_coaster: "🎢",
  roller_skate: "🛼",
  rooster: "🐓",
  rose: "🌹",
  rosette: "🏵️",
  rotating_light: "🚨",
  round_pushpin: "📍",
  rowboat: "🚣",
  rugby_football: "🏉",
  runner: "🏃",
  running_shirt_with_sash: "🎽",
  sa: "🈂️",
  safety_pin: "🧷",
  safety_vest: "🦺",
  sagittarius: "♐",
  sailboat: "⛵",
  sake: "🍶",
  salad: "🥗",
  salt: "🧂",
  sandal: "👡",
  sandwich: "🥪",
  santa: "🎅",
  sari: "🥻",
  satellite: "📡",
  satellite_orbital: "🛰️",
  sauropod: "🦕",
  saxophone: "🎷",
  scales: "⚖️",
  scarf: "🧣",
  school: "🏫",
  school_satchel: "🎒",
  scientist: "🧑‍🔬",
  scissors: "✂️",
  scooter: "🛴",
  scorpion: "🦂",
  scorpius: "♏",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  screwdriver: "🪛",
  scroll: "📜",
  seal: "🦭",
  seat: "💺",
  second_place: "🥈",
  secret: "㊙️",
  see_no_evil: "🙈",
  seedling: "🌱",
  selfie: "🤳",
  service_dog: "🐕‍🦺",
  sewing_needle: "🪡",
  shamrock: "☘️",
  shark: "🦈",
  shaved_ice: "🍧",
  sheep: "🐑",
  shell: "🐚",
  shield: "🛡️",
  shinto_shrine: "⛩️",
  ship: "🚢",
  shirt: "👕",
  shopping_bags: "🛍️",
  shopping_cart: "🛒",
  shorts: "🩳",
  shower: "🚿",
  shrimp: "🦐",
  shrug: "🤷",
  signal_strength: "📶",
  singer: "🧑‍🎤",
  six_pointed_star: "🔯",
  skateboard: "🛹",
  ski: "🎿",
  skier: "⛷️",
  skunk: "🦨",
  sled: "🛷",
  sleeping_accommodation: "🛌",
  slight_smile: "🙂",
  slot_machine: "🎰",
  sloth: "🦥",
  small_blue_diamond: "🔹",
  small_orange_diamond: "🔸",
  small_red_triangle: "🔺",
  small_red_triangle_down: "🔻",
  smile: "😄",
  smiling_imp: "😈",
  smoking: "🚬",
  snail: "🐌",
  snake: "🐍",
  snowboarder: "🏂",
  snowflake: "❄️",
  snowman: "⛄",
  snowman2: "☃️",
  soap: "🧼",
  sob: "😭",
  soccer: "⚽",
  socks: "🧦",
  softball: "🥎",
  soon: "🔜",
  sos: "🆘",
  sound: "🔉",
  spades: "♠️",
  spaghetti: "🍝",
  sparkle: "❇️",
  sparkler: "🎇",
  sparkles: "✨",
  sparkling_heart: "💖",
  speak_no_evil: "🙊",
  speaker: "🔈",
  speaking_head: "🗣️",
  speech_balloon: "💬",
  speech_left: "🗨️",
  speedboat: "🚤",
  spider: "🕷️",
  spider_web: "🕸️",
  sponge: "🧽",
  spoon: "🥄",
  spy: "🕵️",
  squeeze_bottle: "🧴",
  squid: "🦑",
  stadium: "🏟️",
  star: "⭐",
  star2: "🌟",
  star_and_crescent: "☪️",
  star_of_david: "✡️",
  stars: "🌠",
  station: "🚉",
  statue_of_liberty: "🗽",
  steam_locomotive: "🚂",
  stethoscope: "🩺",
  stew: "🍲",
  stop_button: "⏹️",
  stop_sign: "🛑",
  stopwatch: "⏱️",
  straight_ruler: "📏",
  strawberry: "🍓",
  stuck_out_tongue: "😛",
  stuck_out_tongue_winking_eye: "😜",
  student: "🧑‍🎓",
  stuffed_pita: "🥙",
  sun_with_face: "🌞",
  sunflower: "🌻",
  sunglasses: "😎",
  sunny: "☀️",
  sunrise: "🌅",
  sunrise_over_mountains: "🌄",
  superhero: "🦸",
  supervillain: "🦹",
  surfer: "🏄",
  sushi: "🍣",
  suspension_railway: "🚟",
  swan: "🦢",
  sweat: "😓",
  sweat_drops: "💦",
  sweat_smile: "😅",
  sweet_potato: "🍠",
  swimmer: "🏊",
  symbols: "🔣",
  synagogue: "🕍",
  syringe: "💉",
  t_rex: "🦖",
  taco: "🌮",
  tada: "🎉",
  takeout_box: "🥡",
  tamale: "🫔",
  tanabata_tree: "🎋",
  tangerine: "🍊",
  taurus: "♉",
  taxi: "🚕",
  tea: "🍵",
  teacher: "🧑‍🏫",
  teapot: "🫖",
  technologist: "🧑‍💻",
  teddy_bear: "🧸",
  telephone: "☎️",
  telephone_receiver: "📞",
  telescope: "🔭",
  tennis: "🎾",
  tent: "⛺",
  test_tube: "🧪",
  thermometer: "🌡️",
  third_place: "🥉",
  thong_sandal: "🩴",
  thought_balloon: "💭",
  thread: "🧵",
  thumbdown: "👎",
  thumbup: "👍",
  thunder_cloud_rain: "⛈️",
  ticket: "🎫",
  tickets: "🎟️",
  tiger: "🐯",
  tiger2: "🐅",
  timer: "⏲️",
  tm: "™️",
  toilet: "🚽",
  tokyo_tower: "🗼",
  tomato: "🍅",
  tongue: "👅",
  toolbox: "🧰",
  tools: "🛠️",
  tooth: "🦷",
  toothbrush: "🪥",
  top: "🔝",
  tophat: "🎩",
  trackball: "🖲️",
  tractor: "🚜",
  traffic_light: "🚥",
  train: "🚋",
  train2: "🚆",
  tram: "🚊",
  transgender_flag: "🏳️‍⚧️",
  transgender_symbol: "⚧",
  triangular_flag_on_post: "🚩",
  triangular_ruler: "📐",
  trident: "🔱",
  trolleybus: "🚎",
  trophy: "🏆",
  tropical_drink: "🍹",
  tropical_fish: "🐠",
  truck: "🚚",
  trumpet: "🎺",
  tulip: "🌷",
  turkey: "🦃",
  turtle: "🐢",
  tuxedo: "🤵",
  tv: "📺",
  twisted_rightwards_arrows: "🔀",
  two_hearts: "💕",
  two_men_holding_hands: "👬",
  two_women_holding_hands: "👭",
  u5272: "🈹",
  u5408: "🈴",
  u55b6: "🈺",
  u6307: "🈯",
  u6708: "🈷️",
  u6709: "🈶",
  u6e80: "🈵",
  u7121: "🈚",
  u7533: "🈸",
  u7981: "🈲",
  u7a7a: "🈳",
  umbrella: "☔",
  umbrella2: "☂️",
  unamused: "😒",
  underage: "🔞",
  unicorn: "🦄",
  united_nations: "🇺🇳",
  unlock: "🔓",
  up: "🆙",
  urn: "⚱️",
  v: "✌️",
  vampire: "🧛",
  vertical_traffic_light: "🚦",
  vhs: "📼",
  vibration_mode: "📳",
  video_camera: "📹",
  video_game: "🎮",
  violin: "🎻",
  virgo: "♍",
  volcano: "🌋",
  volleyball: "🏐",
  vs: "🆚",
  vulcan: "🖖",
  waffle: "🧇",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  walking: "🚶",
  waning_crescent_moon: "🌘",
  waning_gibbous_moon: "🌖",
  warning: "⚠️",
  wastebasket: "🗑️",
  watch: "⌚",
  water_buffalo: "🐃",
  water_polo: "🤽",
  watermelon: "🍉",
  wave: "👋",
  wavy_dash: "〰️",
  waxing_crescent_moon: "🌒",
  waxing_gibbous_moon: "🌔",
  wc: "🚾",
  wedding: "💒",
  whale: "🐳",
  whale2: "🐋",
  wheel_of_dharma: "☸️",
  wheelchair: "♿",
  whisky: "🥃",
  white_check_mark: "✅",
  white_circle: "⚪",
  white_flower: "💮",
  white_heart: "🤍",
  white_large_square: "⬜",
  white_medium_small_square: "◽",
  white_medium_square: "◻️",
  white_small_square: "▫️",
  white_square_button: "🔳",
  white_sun_cloud: "🌥️",
  white_sun_rain_cloud: "🌦️",
  white_sun_small_cloud: "🌤️",
  wilted_rose: "🥀",
  wind_blowing_face: "🌬️",
  wind_chime: "🎐",
  window: "🪟",
  wine_glass: "🍷",
  wink: "😉",
  wolf: "🐺",
  woman: "👩",
  woman_and_man_holding_hands: "👫",
  woman_artist: "👩‍🎨",
  woman_astronaut: "👩‍🚀",
  woman_bald: "👩‍🦲",
  woman_biking: "🚴‍♀️",
  woman_bouncing_ball: "⛹️‍♀️",
  woman_bowing: "🙇‍♀️",
  woman_cartwheeling: "🤸‍♀️",
  woman_climbing: "🧗‍♀️",
  woman_construction_worker: "👷‍♀️",
  woman_cook: "👩‍🍳",
  woman_curly_haired: "👩‍🦱",
  woman_detective: "🕵️‍♀️",
  woman_elf: "🧝‍♀️",
  woman_facepalming: "🤦‍♀️",
  woman_factory_worker: "👩‍🏭",
  woman_fairy: "🧚‍♀️",
  woman_farmer: "👩‍🌾",
  woman_feeding_baby: "👩‍🍼",
  woman_firefighter: "👩‍🚒",
  woman_frowning: "🙍‍♀️",
  woman_genie: "🧞‍♀️",
  woman_gesturing_no: "🙅‍♀️",
  woman_gesturing_ok: "🙆‍♀️",
  woman_getting_face_massage: "💆‍♀️",
  woman_getting_haircut: "💇‍♀️",
  woman_golfing: "🏌️‍♀️",
  woman_guard: "💂‍♀️",
  woman_health_worker: "👩‍⚕️",
  woman_in_lotus_position: "🧘‍♀️",
  woman_in_manual_wheelchair: "👩‍🦽",
  woman_in_motorized_wheelchair: "👩‍🦼",
  woman_in_steamy_room: "🧖‍♀️",
  woman_in_tuxedo: "🤵‍♀️",
  woman_judge: "👩‍⚖️",
  woman_juggling: "🤹‍♀️",
  woman_kneeling: "🧎‍♀️",
  woman_lifting_weights: "🏋️‍♀️",
  woman_mage: "🧙‍♀️",
  woman_mechanic: "👩‍🔧",
  woman_mountain_biking: "🚵‍♀️",
  woman_office_worker: "👩‍💼",
  woman_pilot: "👩‍✈️",
  woman_playing_handball: "🤾‍♀️",
  woman_playing_water_polo: "🤽‍♀️",
  woman_police_officer: "👮‍♀️",
  woman_pouting: "🙎‍♀️",
  woman_raising_hand: "🙋‍♀️",
  woman_red_haired: "👩‍🦰",
  woman_rowing_boat: "🚣‍♀️",
  woman_running: "🏃‍♀️",
  woman_scientist: "👩‍🔬",
  woman_shrugging: "🤷‍♀️",
  woman_singer: "👩‍🎤",
  woman_standing: "🧍‍♀️",
  woman_student: "👩‍🎓",
  woman_superhero: "🦸‍♀️",
  woman_supervillain: "🦹‍♀️",
  woman_surfing: "🏄‍♀️",
  woman_swimming: "🏊‍♀️",
  woman_teacher: "👩‍🏫",
  woman_technologist: "👩‍💻",
  woman_tipping_hand: "💁‍♀️",
  woman_vampire: "🧛‍♀️",
  woman_walking: "🚶‍♀️",
  woman_wearing_turban: "👳‍♀️",
  woman_white_haired: "👩‍🦳",
  woman_with_headscarf: "🧕",
  woman_with_probing_cane: "👩‍🦯",
  woman_zombie: "🧟‍♀️",
  womans_clothes: "👚",
  womans_flat_shoe: "🥿",
  womans_hat: "👒",
  women_holding_hands: "👭",
  women_with_bunny_ears_partying: "👯‍♀️",
  women_wrestling: "🤼‍♀️",
  womens: "🚺",
  wood: "🪵",
  worm: "🪱",
  worship_symbol: "🛐",
  wrench: "🔧",
  wrestlers: "🤼",
  writing_hand: "✍️",
  x: "❌",
  yarn: "🧶",
  yellow_circle: "🟡",
  yellow_heart: "💛",
  yellow_square: "🟨",
  yen: "💴",
  yin_yang: "☯️",
  yo_yo: "🪀",
  zap: "⚡",
  zebra: "🦓",
  zombie: "🧟",
  zzz: "💤",
};

const ALIAS: Record<string, string> = {
  "+1": "thumbup",
  "-1": "thumbdown",
  admission_tickets: "tickets",
  atom_symbol: "atom",
  baguette_bread: "french_bread",
  ballot_box_with_ballot: "ballot_box",
  basketball_player: "person_with_ball",
  beach_with_umbrella: "beach",
  bellhop_bell: "bellhop",
  biohazard_sign: "biohazard",
  bottle_with_popping_cork: "champagne",
  bow_and_arrow: "archery",
  boxing_gloves: "boxing_glove",
  building_construction: "construction_site",
  call_me_hand: "call_me",
  card_file_box: "card_box",
  card_index_dividers: "dividers",
  champagne_glass: "clinking_glass",
  cheese_wedge: "cheese",
  city_sunrise: "city_sunset",
  cloud_with_lightning: "cloud_lightning",
  cloud_with_rain: "cloud_rain",
  cloud_with_snow: "cloud_snow",
  cloud_with_tornado: "cloud_tornado",
  couch_and_lamp: "couch",
  couple_with_heart_mm: "couple_mm",
  couple_with_heart_ww: "couple_ww",
  couplekiss_mm: "kiss_mm",
  couplekiss_ww: "kiss_ww",
  cricket_bat_ball: "cricket_game",
  custard: "flan",
  dagger_knife: "dagger",
  derelict_house_building: "house_abandoned",
  desert_island: "island",
  desktop_computer: "desktop",
  detective: "spy",
  double_vertical_bar: "pause_button",
  dove_of_peace: "dove",
  drum_with_drumsticks: "drum",
  e_mail: "email",
  eject_symbol: "eject",
  expecting_woman: "pregnant_woman",
  face_palm: "facepalm",
  fencing: "fencer",
  film_projector: "projector",
  first_place_medal: "first_place",
  flame: "fire",
  fork_and_knife_with_plate: "fork_knife_plate",
  fox_face: "fox",
  frame_with_picture: "frame_photo",
  funeral_urn: "urn",
  gay_pride_flag: "rainbow_flag",
  glass_of_milk: "milk",
  goal_net: "goal",
  green_salad: "salad",
  guardsman: "guard",
  hammer_and_pick: "hammer_pick",
  hammer_and_wrench: "tools",
  hand_with_index_and_middle_finger_crossed: "fingers_crossed",
  heavy_heart_exclamation_mark_ornament: "heart_exclamation",
  helmet_with_white_cross: "helmet_with_cross",
  hot_dog: "hotdog",
  house_buildings: "homes",
  information_desk_person: "person_tipping_hand",
  juggling: "juggler",
  kayak: "canoe",
  keycap_asterisk: "asterisk",
  kiwifruit: "kiwi",
  latin_cross: "cross",
  left_facing_fist: "left_fist",
  left_speech_bubble: "speech_left",
  linked_paperclips: "paperclips",
  lion_face: "lion",
  lower_left_ballpoint_pen: "pen_ballpoint",
  lower_left_crayon: "crayon",
  lower_left_fountain_pen: "pen_fountain",
  lower_left_paintbrush: "paintbrush",
  man_dancing: "male_dancer",
  man_in_business_suit_levitating: "levitate",
  man_with_chinese_cap: "man_with_gua_pi_mao",
  mantlepiece_clock: "clock",
  martial_arts_uniform: "karate_uniform",
  mobile_phone: "iphone",
  mother_christmas: "mrs_claus",
  motor_scooter: "motorbike",
  national_park: "park",
  octagonal_sign: "stop_sign",
  oil_drum: "oil",
  old_key: "key2",
  older_woman: "grandma",
  passenger_ship: "cruise_ship",
  paw_prints: "feet",
  peace_symbol: "peace",
  pencil: "memo",
  people_with_bunny_ears_partying: "dancers",
  people_wrestling: "wrestlers",
  person_biking: "bicyclist",
  person_bouncing_ball: "person_with_ball",
  person_bowing: "bow",
  person_dark_skin_tone_bald: "person_tone5_bald",
  person_dark_skin_tone_curly_hair: "person_tone5_curly_hair",
  person_dark_skin_tone_red_hair: "person_tone5_red_hair",
  person_dark_skin_tone_white_hair: "person_tone5_white_hair",
  person_doing_cartwheel: "cartwheel",
  person_facepalming: "facepalm",
  person_fencing: "fencer",
  person_gesturing_no: "no_good",
  person_gesturing_ok: "ok_woman",
  person_getting_haircut: "haircut",
  person_getting_massage: "massage",
  person_golfing: "golfer",
  person_juggling: "juggler",
  person_lifting_weights: "lifter",
  person_light_skin_tone_bald: "person_tone1_bald",
  person_light_skin_tone_curly_hair: "person_tone1_curly_hair",
  person_light_skin_tone_red_hair: "person_tone1_red_hair",
  person_light_skin_tone_white_hair: "person_tone1_white_hair",
  person_medium_dark_skin_tone_bald: "person_tone4_bald",
  person_medium_dark_skin_tone_curly_hair: "person_tone4_curly_hair",
  person_medium_dark_skin_tone_red_hair: "person_tone4_red_hair",
  person_medium_dark_skin_tone_white_hair: "person_tone4_white_hair",
  person_medium_light_skin_tone_bald: "person_tone2_bald",
  person_medium_light_skin_tone_curly_hair: "person_tone2_curly_hair",
  person_medium_light_skin_tone_red_hair: "person_tone2_red_hair",
  person_medium_light_skin_tone_white_hair: "person_tone2_white_hair",
  person_medium_skin_tone_bald: "person_tone3_bald",
  person_medium_skin_tone_curly_hair: "person_tone3_curly_hair",
  person_medium_skin_tone_red_hair: "person_tone3_red_hair",
  person_medium_skin_tone_white_hair: "person_tone3_white_hair",
  person_mountain_biking: "mountain_bicyclist",
  person_playing_handball: "handball",
  person_playing_water_polo: "water_polo",
  person_raising_hand: "raising_hand",
  person_rowing_boat: "rowboat",
  person_running: "runner",
  person_shrugging: "shrug",
  person_surfing: "surfer",
  person_swimming: "swimmer",
  person_walking: "walking",
  person_wearing_turban: "man_with_turban",
  person_with_blond_hair: "blond_haired_person",
  person_with_pouting_face: "person_pouting",
  place_of_worship: "worship_symbol",
  police_officer: "cop",
  pudding: "flan",
  racing_car: "race_car",
  racing_motorcycle: "motorcycle",
  radioactive_sign: "radioactive",
  railroad_track: "railway_track",
  raised_back_of_hand: "back_of_hand",
  raised_hand_with_fingers_splayed: "hand_splayed",
  raised_hand_with_part_between_middle_and_ring_fingers: "vulcan",
  reversed_hand_with_middle_finger_extended: "middle_finger",
  rhinoceros: "rhino",
  right_anger_bubble: "anger_right",
  right_facing_fist: "right_fist",
  rolled_up_newspaper: "newspaper2",
  second_place_medal: "second_place",
  shaking_hands: "handshake",
  shallow_pan_of_food: "paella",
  shelled_peanut: "peanuts",
  shopping_trolley: "shopping_cart",
  sign_of_the_horns: "metal",
  sleuth_or_spy: "spy",
  small_airplane: "airplane_small",
  snow_capped_mountain: "mountain_snow",
  speaking_head_in_silhouette: "speaking_head",
  spiral_calendar_pad: "calendar_spiral",
  spiral_note_pad: "notepad_spiral",
  sports_medal: "medal",
  studio_microphone: "microphone2",
  stuffed_flatbread: "stuffed_pita",
  table_tennis: "ping_pong",
  third_place_medal: "third_place",
  three_button_mouse: "mouse_three_button",
  thumbsdown: "thumbdown",
  thumbsup: "thumbup",
  thunder_cloud_and_rain: "thunder_cloud_rain",
  timer_clock: "timer",
  track_next: "next_track",
  track_previous: "previous_track",
  tumbler_glass: "whisky",
  umbrella_on_ground: "beach_umbrella",
  unicorn_face: "unicorn",
  weight_lifter: "lifter",
  white_sun_behind_cloud: "white_sun_cloud",
  white_sun_behind_cloud_with_rain: "white_sun_rain_cloud",
  white_sun_with_small_cloud: "white_sun_small_cloud",
  wilted_flower: "wilted_rose",
  woman_with_veil: "bride_with_veil",
  world_map: "map",
  wrestling: "wrestlers",
};

/**
 * Tone rules: stem -> [insertIndices, deleteIndices]
 * Indices are UTF-16 code unit offsets into the base emoji string.
 * deleteIndices are almost always for removing U+FE0F (VS16) when the toned form omits it.
 */
const TONE_RULES: Record<
  string,
  readonly [readonly number[], readonly number[]]
> = {
  _1: [[2], []],
  adult: [[2], []],
  angel: [[2], []],
  artist: [[2], []],
  astronaut: [[2], []],
  baby: [[2], []],
  back_of_hand: [[2], []],
  bath: [[2], []],
  bearded_person: [[2], []],
  bicyclist: [[2], []],
  blond_haired_man: [[2], []],
  blond_haired_person: [[2], []],
  blond_haired_woman: [[2], []],
  bow: [[2], []],
  boy: [[2], []],
  breast_feeding: [[2], []],
  bride_with_veil: [[2], []],
  call_me: [[2], []],
  cartwheel: [[2], []],
  child: [[2], []],
  clap: [[2], []],
  construction_worker: [[2], []],
  cook: [[2], []],
  cop: [[2], []],
  dancer: [[2], []],
  deaf_man: [[2], []],
  deaf_person: [[2], []],
  deaf_woman: [[2], []],
  ear: [[2], []],
  ear_with_hearing_aid: [[2], []],
  elf: [[2], []],
  facepalm: [[2], []],
  factory_worker: [[2], []],
  fairy: [[2], []],
  farmer: [[2], []],
  fingers_crossed: [[2], []],
  firefighter: [[2], []],
  fist: [[1], []],
  foot: [[2], []],
  girl: [[2], []],
  golfer: [[2], [2]],
  grandma: [[2], []],
  guard: [[2], []],
  haircut: [[2], []],
  hand_splayed: [[2], [2]],
  hand_with_index_and_middle_fingers_crossed: [[2], []],
  handball: [[2], []],
  health_worker: [[2], []],
  horse_racing: [[2], []],
  judge: [[2], []],
  juggler: [[2], []],
  left_fist: [[2], []],
  leg: [[2], []],
  levitate: [[2], [2]],
  lifter: [[2], [2]],
  love_you_gesture: [[2], []],
  mage: [[2], []],
  male_dancer: [[2], []],
  man: [[2], []],
  man_artist: [[2], []],
  man_astronaut: [[2], []],
  man_bald: [[2], []],
  man_biking: [[2], []],
  man_bouncing_ball: [[1], [1]],
  man_bowing: [[2], []],
  man_cartwheeling: [[2], []],
  man_climbing: [[2], []],
  man_construction_worker: [[2], []],
  man_cook: [[2], []],
  man_curly_haired: [[2], []],
  man_detective: [[2], [2]],
  man_elf: [[2], []],
  man_facepalming: [[2], []],
  man_factory_worker: [[2], []],
  man_fairy: [[2], []],
  man_farmer: [[2], []],
  man_feeding_baby: [[2], []],
  man_firefighter: [[2], []],
  man_frowning: [[2], []],
  man_gesturing_no: [[2], []],
  man_gesturing_ok: [[2], []],
  man_getting_face_massage: [[2], []],
  man_getting_haircut: [[2], []],
  man_golfing: [[2], [2]],
  man_guard: [[2], []],
  man_health_worker: [[2], []],
  man_in_lotus_position: [[2], []],
  man_in_manual_wheelchair: [[2], []],
  man_in_motorized_wheelchair: [[2], []],
  man_in_steamy_room: [[2], []],
  man_in_tuxedo: [[2], []],
  man_judge: [[2], []],
  man_juggling: [[2], []],
  man_kneeling: [[2], []],
  man_lifting_weights: [[2], [2]],
  man_mage: [[2], []],
  man_mechanic: [[2], []],
  man_mountain_biking: [[2], []],
  man_office_worker: [[2], []],
  man_pilot: [[2], []],
  man_playing_handball: [[2], []],
  man_playing_water_polo: [[2], []],
  man_police_officer: [[2], []],
  man_pouting: [[2], []],
  man_raising_hand: [[2], []],
  man_red_haired: [[2], []],
  man_rowing_boat: [[2], []],
  man_running: [[2], []],
  man_scientist: [[2], []],
  man_shrugging: [[2], []],
  man_singer: [[2], []],
  man_standing: [[2], []],
  man_student: [[2], []],
  man_superhero: [[2], []],
  man_supervillain: [[2], []],
  man_surfing: [[2], []],
  man_swimming: [[2], []],
  man_teacher: [[2], []],
  man_technologist: [[2], []],
  man_tipping_hand: [[2], []],
  man_vampire: [[2], []],
  man_walking: [[2], []],
  man_wearing_turban: [[2], []],
  man_white_haired: [[2], []],
  man_with_gua_pi_mao: [[2], []],
  man_with_probing_cane: [[2], []],
  man_with_turban: [[2], []],
  man_with_veil: [[2], []],
  massage: [[2], []],
  mechanic: [[2], []],
  mermaid: [[2], []],
  merman: [[2], []],
  merperson: [[2], []],
  metal: [[2], []],
  middle_finger: [[2], []],
  mountain_bicyclist: [[2], []],
  mrs_claus: [[2], []],
  muscle: [[2], []],
  mx_claus: [[2], []],
  nail_care: [[2], []],
  ninja: [[2], []],
  no_good: [[2], []],
  nose: [[2], []],
  office_worker: [[2], []],
  ok_hand: [[2], []],
  ok_woman: [[2], []],
  older_adult: [[2], []],
  older_man: [[2], []],
  open_hands: [[2], []],
  people_holding_hands: [[2, 8], []],
  person_climbing: [[2], []],
  person_feeding_baby: [[2], []],
  person_frowning: [[2], []],
  person_in_bed: [[2], []],
  person_in_lotus_position: [[2], []],
  person_in_manual_wheelchair: [[2], []],
  person_in_motorized_wheelchair: [[2], []],
  person_in_steamy_room: [[2], []],
  person_in_tuxedo: [[2], []],
  person_kneeling: [[2], []],
  person_pouting: [[2], []],
  person_standing: [[2], []],
  person_tipping_hand: [[2], []],
  person_with_ball: [[1], [1]],
  person_with_probing_cane: [[2], []],
  person_with_veil: [[2], []],
  pilot: [[2], []],
  pinched_fingers: [[2], []],
  pinching_hand: [[2], []],
  point_down: [[2], []],
  point_left: [[2], []],
  point_right: [[2], []],
  point_up: [[1], [1]],
  point_up_2: [[2], []],
  pray: [[2], []],
  pregnant_woman: [[2], []],
  prince: [[2], []],
  princess: [[2], []],
  punch: [[2], []],
  raised_hand: [[1], []],
  raised_hands: [[2], []],
  raising_hand: [[2], []],
  right_fist: [[2], []],
  rowboat: [[2], []],
  runner: [[2], []],
  santa: [[2], []],
  scientist: [[2], []],
  selfie: [[2], []],
  shrug: [[2], []],
  singer: [[2], []],
  snowboarder: [[2], []],
  spy: [[2], [2]],
  student: [[2], []],
  superhero: [[2], []],
  supervillain: [[2], []],
  surfer: [[2], []],
  swimmer: [[2], []],
  teacher: [[2], []],
  technologist: [[2], []],
  thumbdown: [[2], []],
  thumbup: [[2], []],
  tuxedo: [[2], []],
  v: [[1], [1]],
  vampire: [[2], []],
  vulcan: [[2], []],
  walking: [[2], []],
  water_polo: [[2], []],
  wave: [[2], []],
  woman: [[2], []],
  woman_artist: [[2], []],
  woman_astronaut: [[2], []],
  woman_bald: [[2], []],
  woman_biking: [[2], []],
  woman_bouncing_ball: [[1], [1]],
  woman_bowing: [[2], []],
  woman_cartwheeling: [[2], []],
  woman_climbing: [[2], []],
  woman_construction_worker: [[2], []],
  woman_cook: [[2], []],
  woman_curly_haired: [[2], []],
  woman_detective: [[2], [2]],
  woman_elf: [[2], []],
  woman_facepalming: [[2], []],
  woman_factory_worker: [[2], []],
  woman_fairy: [[2], []],
  woman_farmer: [[2], []],
  woman_feeding_baby: [[2], []],
  woman_firefighter: [[2], []],
  woman_frowning: [[2], []],
  woman_gesturing_no: [[2], []],
  woman_gesturing_ok: [[2], []],
  woman_getting_face_massage: [[2], []],
  woman_getting_haircut: [[2], []],
  woman_golfing: [[2], [2]],
  woman_guard: [[2], []],
  woman_health_worker: [[2], []],
  woman_in_lotus_position: [[2], []],
  woman_in_manual_wheelchair: [[2], []],
  woman_in_motorized_wheelchair: [[2], []],
  woman_in_steamy_room: [[2], []],
  woman_in_tuxedo: [[2], []],
  woman_judge: [[2], []],
  woman_juggling: [[2], []],
  woman_kneeling: [[2], []],
  woman_lifting_weights: [[2], [2]],
  woman_mage: [[2], []],
  woman_mechanic: [[2], []],
  woman_mountain_biking: [[2], []],
  woman_office_worker: [[2], []],
  woman_pilot: [[2], []],
  woman_playing_handball: [[2], []],
  woman_playing_water_polo: [[2], []],
  woman_police_officer: [[2], []],
  woman_pouting: [[2], []],
  woman_raising_hand: [[2], []],
  woman_red_haired: [[2], []],
  woman_rowing_boat: [[2], []],
  woman_running: [[2], []],
  woman_scientist: [[2], []],
  woman_shrugging: [[2], []],
  woman_singer: [[2], []],
  woman_standing: [[2], []],
  woman_student: [[2], []],
  woman_superhero: [[2], []],
  woman_supervillain: [[2], []],
  woman_surfing: [[2], []],
  woman_swimming: [[2], []],
  woman_teacher: [[2], []],
  woman_technologist: [[2], []],
  woman_tipping_hand: [[2], []],
  woman_vampire: [[2], []],
  woman_walking: [[2], []],
  woman_wearing_turban: [[2], []],
  woman_white_haired: [[2], []],
  woman_with_headscarf: [[2], []],
  woman_with_probing_cane: [[2], []],
  writing_hand: [[1], [1]],
};

/**
 * Rare exceptions where toned forms aren't representable by "insert modifier(s) + delete FE0F".
 * Keyed by normalized suffix: stem + "_toneX" or stem + "_toneX_toneY".
 */
const EXPLICIT_TONES: Record<string, string> = {
  men_holding_hands_tone1: "👬🏻",
  men_holding_hands_tone1_tone2: "👨🏻‍🤝‍👨🏼",
  men_holding_hands_tone1_tone3: "👨🏻‍🤝‍👨🏽",
  men_holding_hands_tone1_tone4: "👨🏻‍🤝‍👨🏾",
  men_holding_hands_tone1_tone5: "👨🏻‍🤝‍👨🏿",
  men_holding_hands_tone2: "👬🏼",
  men_holding_hands_tone2_tone1: "👨🏼‍🤝‍👨🏻",
  men_holding_hands_tone2_tone3: "👨🏼‍🤝‍👨🏽",
  men_holding_hands_tone2_tone4: "👨🏼‍🤝‍👨🏾",
  men_holding_hands_tone2_tone5: "👨🏼‍🤝‍👨🏿",
  men_holding_hands_tone3: "👬🏽",
  men_holding_hands_tone3_tone1: "👨🏽‍🤝‍👨🏻",
  men_holding_hands_tone3_tone2: "👨🏽‍🤝‍👨🏼",
  men_holding_hands_tone3_tone4: "👨🏽‍🤝‍👨🏾",
  men_holding_hands_tone3_tone5: "👨🏽‍🤝‍👨🏿",
  men_holding_hands_tone4: "👬🏾",
  men_holding_hands_tone4_tone1: "👨🏾‍🤝‍👨🏻",
  men_holding_hands_tone4_tone2: "👨🏾‍🤝‍👨🏼",
  men_holding_hands_tone4_tone3: "👨🏾‍🤝‍👨🏽",
  men_holding_hands_tone4_tone5: "👨🏾‍🤝‍👨🏿",
  men_holding_hands_tone5: "👬🏿",
  men_holding_hands_tone5_tone1: "👨🏿‍🤝‍👨🏻",
  men_holding_hands_tone5_tone2: "👨🏿‍🤝‍👨🏼",
  men_holding_hands_tone5_tone3: "👨🏿‍🤝‍👨🏽",
  men_holding_hands_tone5_tone4: "👨🏿‍🤝‍👨🏾",
  woman_and_man_holding_hands_tone1: "👫🏻",
  woman_and_man_holding_hands_tone1_tone2: "👩🏻‍🤝‍👨🏼",
  woman_and_man_holding_hands_tone1_tone3: "👩🏻‍🤝‍👨🏽",
  woman_and_man_holding_hands_tone1_tone4: "👩🏻‍🤝‍👨🏾",
  woman_and_man_holding_hands_tone1_tone5: "👩🏻‍🤝‍👨🏿",
  woman_and_man_holding_hands_tone2: "👫🏼",
  woman_and_man_holding_hands_tone2_tone1: "👩🏼‍🤝‍👨🏻",
  woman_and_man_holding_hands_tone2_tone3: "👩🏼‍🤝‍👨🏽",
  woman_and_man_holding_hands_tone2_tone4: "👩🏼‍🤝‍👨🏾",
  woman_and_man_holding_hands_tone2_tone5: "👩🏼‍🤝‍👨🏿",
  woman_and_man_holding_hands_tone3: "👫🏽",
  woman_and_man_holding_hands_tone3_tone1: "👩🏽‍🤝‍👨🏻",
  woman_and_man_holding_hands_tone3_tone2: "👩🏽‍🤝‍👨🏼",
  woman_and_man_holding_hands_tone3_tone4: "👩🏽‍🤝‍👨🏾",
  woman_and_man_holding_hands_tone3_tone5: "👩🏽‍🤝‍👨🏿",
  woman_and_man_holding_hands_tone4: "👫🏾",
  woman_and_man_holding_hands_tone4_tone1: "👩🏾‍🤝‍👨🏻",
  woman_and_man_holding_hands_tone4_tone2: "👩🏾‍🤝‍👨🏼",
  woman_and_man_holding_hands_tone4_tone3: "👩🏾‍🤝‍👨🏽",
  woman_and_man_holding_hands_tone4_tone5: "👩🏾‍🤝‍👨🏿",
  woman_and_man_holding_hands_tone5: "👫🏿",
  woman_and_man_holding_hands_tone5_tone1: "👩🏿‍🤝‍👨🏻",
  woman_and_man_holding_hands_tone5_tone2: "👩🏿‍🤝‍👨🏼",
  woman_and_man_holding_hands_tone5_tone3: "👩🏿‍🤝‍👨🏽",
  woman_and_man_holding_hands_tone5_tone4: "👩🏿‍🤝‍👨🏾",
  women_holding_hands_tone1: "👭🏻",
  women_holding_hands_tone1_tone2: "👩🏻‍🤝‍👩🏼",
  women_holding_hands_tone1_tone3: "👩🏻‍🤝‍👩🏽",
  women_holding_hands_tone1_tone4: "👩🏻‍🤝‍👩🏾",
  women_holding_hands_tone1_tone5: "👩🏻‍🤝‍👩🏿",
  women_holding_hands_tone2: "👭🏼",
  women_holding_hands_tone2_tone1: "👩🏼‍🤝‍👩🏻",
  women_holding_hands_tone2_tone3: "👩🏼‍🤝‍👩🏽",
  women_holding_hands_tone2_tone4: "👩🏼‍🤝‍👩🏾",
  women_holding_hands_tone2_tone5: "👩🏼‍🤝‍👩🏿",
  women_holding_hands_tone3: "👭🏽",
  women_holding_hands_tone3_tone1: "👩🏽‍🤝‍👩🏻",
  women_holding_hands_tone3_tone2: "👩🏽‍🤝‍👩🏼",
  women_holding_hands_tone3_tone4: "👩🏽‍🤝‍👩🏾",
  women_holding_hands_tone3_tone5: "👩🏽‍🤝‍👩🏿",
  women_holding_hands_tone4: "👭🏾",
  women_holding_hands_tone4_tone1: "👩🏾‍🤝‍👩🏻",
  women_holding_hands_tone4_tone2: "👩🏾‍🤝‍👩🏼",
  women_holding_hands_tone4_tone3: "👩🏾‍🤝‍👩🏽",
  women_holding_hands_tone4_tone5: "👩🏾‍🤝‍👩🏿",
  women_holding_hands_tone5: "👭🏿",
  women_holding_hands_tone5_tone1: "👩🏿‍🤝‍👩🏻",
  women_holding_hands_tone5_tone2: "👩🏿‍🤝‍👩🏼",
  women_holding_hands_tone5_tone3: "👩🏿‍🤝‍👩🏽",
  women_holding_hands_tone5_tone4: "👩🏿‍🤝‍👩🏾",
};

const FITZ: readonly string[] = ["", "🏻", "🏼", "🏽", "🏾", "🏿"] as const;

const TONE_SUFFIX_RE =
  /_(tone[1-5]|light_skin_tone|medium_light_skin_tone|medium_skin_tone|medium_dark_skin_tone|dark_skin_tone)(?:_(tone[1-5]|light_skin_tone|medium_light_skin_tone|medium_skin_tone|medium_dark_skin_tone|dark_skin_tone))?$/;

function toneTokenToNumber(token: string): 0 | 1 | 2 | 3 | 4 | 5 {
  switch (token) {
    case "tone1":
    case "light_skin_tone":
      return 1;
    case "tone2":
    case "medium_light_skin_tone":
      return 2;
    case "tone3":
    case "medium_skin_tone":
      return 3;
    case "tone4":
    case "medium_dark_skin_tone":
      return 4;
    case "tone5":
    case "dark_skin_tone":
      return 5;
    default:
      return 0;
  }
}

function maybeFlagFromName(name: string): string | undefined {
  // "flag_" + 2 letters
  if (name.length !== 7) return undefined;
  if (
    name.charCodeAt(0) !== 102 || // f
    name.charCodeAt(1) !== 108 || // l
    name.charCodeAt(2) !== 97 || // a
    name.charCodeAt(3) !== 103 || // g
    name.charCodeAt(4) !== 95 // _
  ) {
    return undefined;
  }
  const c1 = name.charCodeAt(5);
  const c2 = name.charCodeAt(6);
  const a1 = (c1 | 32) - 97;
  const a2 = (c2 | 32) - 97;
  if (a1 < 0 || a1 > 25 || a2 < 0 || a2 > 25) return undefined;
  return String.fromCodePoint(0x1f1e6 + a1, 0x1f1e6 + a2);
}

function maybeRegionalIndicatorFromName(name: string): string | undefined {
  const prefix = "regional_indicator_";
  if (!name.startsWith(prefix) || name.length !== prefix.length + 1)
    return undefined;
  const c = name.charCodeAt(prefix.length);
  const a = (c | 32) - 97;
  if (a < 0 || a > 25) return undefined;
  return String.fromCodePoint(0x1f1e6 + a);
}

const KEYCAP_SUFFIX = "\uFE0F\u20E3";
function maybeKeycapFromName(name: string): string | undefined {
  switch (name) {
    case "zero":
      return "0" + KEYCAP_SUFFIX;
    case "one":
      return "1" + KEYCAP_SUFFIX;
    case "two":
      return "2" + KEYCAP_SUFFIX;
    case "three":
      return "3" + KEYCAP_SUFFIX;
    case "four":
      return "4" + KEYCAP_SUFFIX;
    case "five":
      return "5" + KEYCAP_SUFFIX;
    case "six":
      return "6" + KEYCAP_SUFFIX;
    case "seven":
      return "7" + KEYCAP_SUFFIX;
    case "eight":
      return "8" + KEYCAP_SUFFIX;
    case "nine":
      return "9" + KEYCAP_SUFFIX;
    case "hash":
      return "#" + KEYCAP_SUFFIX;
    case "asterisk":
      return "*" + KEYCAP_SUFFIX;
    case "keycap_ten":
      return "🔟";
    default:
      return undefined;
  }
}

function maybeClockFromName(name: string): string | undefined {
  if (!name.startsWith("clock")) return undefined;
  const rest = name.slice(5);
  if (!rest) return undefined;

  if (rest.endsWith("30")) {
    const hourStr = rest.slice(0, -2);
    const hour = Number(hourStr);
    if (!Number.isInteger(hour) || hour < 1 || hour > 12) return undefined;
    if (String(hour) !== hourStr) return undefined;
    return String.fromCodePoint(0x1f55c + (hour - 1));
  }

  const hour = Number(rest);
  if (!Number.isInteger(hour) || hour < 1 || hour > 12) return undefined;
  if (String(hour) !== rest) return undefined;
  return String.fromCodePoint(0x1f550 + (hour - 1));
}

function applyTone(
  base: string,
  rule: readonly [readonly number[], readonly number[]],
  tones: readonly number[]
): string {
  const ins = rule[0];
  const del = rule[1];

  let out = base;

  // Apply from end so indices stay valid.
  let di = del.length - 1;
  let ii = ins.length - 1;

  while (di >= 0 || ii >= 0) {
    const nextDel = di >= 0 ? del[di] : -1;
    const nextIns = ii >= 0 ? ins[ii] : -1;
    const idx = nextDel > nextIns ? nextDel : nextIns;

    // delete first at idx (important when del and ins share same index)
    while (di >= 0 && del[di] === idx) {
      out = out.slice(0, idx) + out.slice(idx + 1);
      di--;
    }

    // then insert
    while (ii >= 0 && ins[ii] === idx) {
      const tone = tones[ii] ?? tones[0];
      const mod = FITZ[tone] ?? "";
      out = out.slice(0, idx) + mod + out.slice(idx);
      ii--;
    }
  }

  return out;
}

export function getEmoji(input: string): string | undefined {
  if (!input) return undefined;
  let name = input;

  // optional :shortcode: wrapper
  if (
    name.length > 2 &&
    name.charCodeAt(0) === 58 &&
    name.charCodeAt(name.length - 1) === 58
  ) {
    name = name.slice(1, -1);
  }

  // Parse skin tone suffix (1 or 2 tokens)
  let t1: 0 | 1 | 2 | 3 | 4 | 5 = 0;
  let t2: 0 | 1 | 2 | 3 | 4 | 5 = 0;

  const m = TONE_SUFFIX_RE.exec(name);
  if (m) {
    t1 = toneTokenToNumber(m[1]);
    t2 = m[2] ? toneTokenToNumber(m[2]) : 0;
    name = name.slice(0, m.index);
  }

  // Resolve alias on the (tone-less) stem
  const aliased = ALIAS[name];
  if (aliased) name = aliased;

  // Algorithmic (lets us drop hundreds of entries)
  const flag = maybeFlagFromName(name);
  if (flag) return flag;

  const ri = maybeRegionalIndicatorFromName(name);
  if (ri) return ri;

  const kc = maybeKeycapFromName(name);
  if (kc) return kc;

  const clk = maybeClockFromName(name);
  if (clk) return clk;

  const base = BASE[name];
  if (!t1) return base;

  // Prefer rule-based generation
  const rule = TONE_RULES[name];
  if (rule && base) {
    const slots = rule[0].length;
    const tones = slots === 2 ? (t2 ? [t1, t2] : [t1, t1]) : [t1];
    return applyTone(base, rule, tones);
  }

  // Fallback for rare exceptions (normalized key)
  if (t2) {
    return EXPLICIT_TONES[name + "_tone" + t1 + "_tone" + t2];
  }
  return (
    EXPLICIT_TONES[name + "_tone" + t1] ??
    EXPLICIT_TONES[name + "_tone" + t1 + "_tone" + t1]
  );
}
